# Generated by Django 5.0.1 on 2026-01-18 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantRecognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plants/')),
                ('detected_plant_name', models.CharField(blank=True, max_length=200)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ai_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suggested_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plant_recognitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nhận diện cây',
                'verbose_name_plural': 'Nhận diện cây',
                'db_table': 'plant_recognitions',
                'ordering': ['-created_at'],
            },
        ),
    ]
