# Generated by Django 6.0.1 on 2026-01-29 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_recommendation', '0001_initial'),
        ('products', '0002_product_care_time_product_care_tips_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light_condition', models.CharField(blank=True, max_length=20, verbose_name='Điều kiện ánh sáng')),
                ('location_type', models.CharField(blank=True, max_length=20, verbose_name='Vị trí')),
                ('space_required', models.CharField(blank=True, max_length=20, verbose_name='Diện tích')),
                ('care_time', models.CharField(blank=True, max_length=20, verbose_name='Thời gian chăm sóc')),
                ('experience_level', models.CharField(blank=True, max_length=20, verbose_name='Kinh nghiệm')),
                ('feng_shui_meaning', models.CharField(blank=True, max_length=200, verbose_name='Ý nghĩa phong thủy')),
                ('recommendation_scores', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommended_products', models.ManyToManyField(blank=True, related_name='recommendations', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plant_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gợi ý cây cảnh',
                'verbose_name_plural': 'Gợi ý cây cảnh',
                'db_table': 'plant_recommendations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='PlantRecognition',
        ),
    ]
