# Generated by Django 6.0.1 on 2026-01-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='care_time',
            field=models.CharField(blank=True, choices=[('low', 'Ít thời gian'), ('medium', 'Thời gian vừa phải'), ('high', 'Nhiều thời gian')], max_length=20, verbose_name='Thời gian chăm sóc'),
        ),
        migrations.AddField(
            model_name='product',
            name='care_tips',
            field=models.TextField(blank=True, verbose_name='Hướng dẫn chăm sóc'),
        ),
        migrations.AddField(
            model_name='product',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Người mới bắt đầu'), ('intermediate', 'Trung bình'), ('expert', 'Có kinh nghiệm')], max_length=20, verbose_name='Mức độ kinh nghiệm'),
        ),
        migrations.AddField(
            model_name='product',
            name='feng_shui_meaning',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ý nghĩa phong thủy'),
        ),
        migrations.AddField(
            model_name='product',
            name='light_condition',
            field=models.CharField(blank=True, choices=[('high', 'Nhiều ánh sáng'), ('medium', 'Ánh sáng vừa phải'), ('low', 'Ít ánh sáng'), ('shade', 'Bóng râm')], max_length=20, verbose_name='Điều kiện ánh sáng'),
        ),
        migrations.AddField(
            model_name='product',
            name='location_type',
            field=models.CharField(blank=True, choices=[('indoor', 'Trong nhà'), ('outdoor', 'Ngoài trời'), ('both', 'Cả hai')], max_length=20, verbose_name='Vị trí'),
        ),
        migrations.AddField(
            model_name='product',
            name='space_required',
            field=models.CharField(blank=True, choices=[('small', 'Nhỏ (< 1m²)'), ('medium', 'Vừa (1-3m²)'), ('large', 'Lớn (> 3m²)')], max_length=20, verbose_name='Diện tích cần'),
        ),
    ]
